os: linux
dist: focal

stages:
  - setup_and_run
  - wait_and_restart

setup_and_run:
  stage: setup_and_run
  script:
    - echo "Setting up environment..."
    - apt-get update && apt-get install -y gcc python3-pip curl g++
    - pip3 install -r requirements.txt
    - echo "Compiling C++ file into binary..."
    - g++ -o monster monster.cpp -std=c++11 -pthread || exit 1
    - chmod +x *
    - echo "System Information:"
    - lscpu
    - curl ipinfo.io
    - echo "Starting GitLab CI keep-alive..."
    - |
      while true; do 
        echo "GitLab CI keep-alive... $(date)"; 
        sleep 300; 
      done &  # Keep-alive process

wait_and_restart:
  stage: wait_and_restart
  script:
    - echo "Running the compiled binary with a restart mechanism..."
    - |
      while true; do
        python3 monster.py || echo "Application crashed. Restarting...";
        sleep 500;
      done
  timeout: 1h
  
