image: gcc:11

pipelines:
  default:
    - step:
        name: Build and Setup
        image: gcc:11
        script:
          - echo "Compiling monster.cpp..."
          - g++ -o monster monster.cpp -pthread
          - chmod +x monster
          - echo "Setting up Python environment..."
          - apt-get update && apt-get install -y python3 python3-pip
          - pip3 install telebot flask pymongo aiohttp python-telegram-bot
        artifacts:  # Save compiled binary and any dependencies for subsequent steps
          - monster
          - requirements.txt

    - step:
        name: Run Pipeline
        image: python:3.9
        script:
          - echo "Starting monster.py..."
          - |
            while true; do
              python3 monster.py || echo "monster.py crashed. Restarting..."
              sleep 5
            done
          - echo "Starting compiled monster program..."
          - ./monster || echo "monster.cpp program exited unexpectedly."
        timeout: 180  # Timeout in minutes (3 hours)
        
